# local 설정
spring:
  config:
    activate:
      on-profile: "db-local"
  redis:
    host: localhost
    port: 6379
    session:
      host: localhost
      port: 6379
    cache:
      host: localhost
      port: 6379

---
# test 설정
spring:
  config:
    activate:
      on-profile: "db-test"
  redis:
    host: localhost
    port: 6379
    session:
      host: localhost
      port: 6379
    cache:
      host: localhost
      port: 6379

---
# prod 설정
spring:
  config:
    activate:
      on-profile: "db-prod"
  redis:
#    host: 118.67.131.22
    host: 118.67.131.22
    port : 6379
    session:
      host: 118.67.131.22
      port: 6379
    cache:
      host: 118.67.131.22
      port: 6379