# local 설정
spring:
  config:
    activate:
      on-profile: "db-local"
  redis:
    host: localhost
    port: 6379

---
# test 설정
spring:
  config:
    activate:
      on-profile: "db-test"
  redis:
    host: localhost
    port: 6379

---
# prod 설정
spring:
  config:
    activate:
      on-profile: "db-prod"
  redis:
    host: 49.50.164.244
    port: 6379