server:
  port: 1024
  tomcat:
    threads:
      max: 500
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
